### ISSUE TITLE
PiT 24.8: latest does not compile with v24.8.0.alpha4

### ISSUE THREAD

**Issue by manolo** [vaadin/docs#4248]
There are changes coming with v24.8.0.alpha4 in upload component that breaks the latest branch

```
git checkout latest
rm -rf node_modules
mvn -B -q versions:set-property -Dproperty=vaadin.version -DnewVersion=24.8.0.alpha4 -DgenerateBackupPoms=false
mvn -U -ntp install -Pproduction
```

```
[ERROR] frontend/demo/component/upload/react/upload-all-files.tsx(17,5): error TS18048: 'uploadRef.current.i18n.addFiles' is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/react/upload-auto-upload-disabled.tsx(16,5): error TS18048: 'uploadRef.current.i18n.addFiles' is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/react/upload-error-messages.tsx(29,5): error TS18048: 'uploadCaution.current.i18n.uploading' is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/react/upload-error-messages.tsx(29,5): error TS18048: 'uploadCaution.current.i18n.uploading.error' is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/react/upload-error-messages.tsx(40,5): error TS18048: 'uploadRecommended.current.i18n.uploading' is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/react/upload-error-messages.tsx(40,5): error TS18048: 'uploadRecommended.current.i18n.uploading.error' is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-all-files.ts(25,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-auto-upload-disabled.ts(24,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-button-theme-variant.ts(31,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-error-messages.ts(36,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-error-messages.ts(36,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-error-messages.ts(39,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-error-messages.ts(39,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-file-count.ts(33,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-file-format.ts(33,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-file-format.ts(34,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-file-format.ts(35,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-file-size.ts(33,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-helper.ts(34,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-helper.ts(35,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-helper.ts(36,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-labelling.ts(24,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-labelling.ts(25,5): error TS2532: Object is possibly 'undefined'.
[ERROR] frontend/demo/component/upload/upload-labelling.ts(26,5): error TS2532: Object is possibly 'undefined'.
```
