### ISSUE TITLE
PiT 24.5: hilla errrors, branch `next` does not compiles with `24.5.0.alpha5`

### ISSUE THREAD

**Issue by manolo** [vaadin/docs#3541]
Update vaadin version in `next` branch and compile it:
```
git checkout next
mvn -B -q versions:set-property -Dproperty=vaadin.version -DnewVersion=24.5.0.alpha5 -DgenerateBackupPoms=false
mvn -U -ntp install -Pproduction
```
Errors in console are related to hilla demos
```
[ERROR] frontend/demo/component/upload/react/upload-all-files.tsx(17,23): error TS2339: Property 'i18n' does not exist on type 'Upload'.
[ERROR] frontend/demo/component/upload/react/upload-all-files.tsx(18,23): error TS2339: Property 'i18n' does not exist on type 'Upload'.
[ERROR] frontend/demo/component/upload/react/upload-all-files.tsx(18,53): error TS2339: Property 'i18n' does not exist on type 'Upload'.
[ERROR] frontend/demo/component/upload/react/upload-all-files.tsx(26,15): error TS2322: Type '{ noAuto: true; ref: RefObject<Upload>; files: UploadFile[]; }' is not assignable to type 'IntrinsicAttributes & Partial<ThemedWebComponentProps<Upload, Readonly<{ onFileReject: EventName<UploadFileRejectEvent>; onUploadAbort: EventName<UploadAbortEvent>; ... 9 more ...; onMaxFilesReachedChanged: EventName<...>; }>>> & RefAttributes<...>'.
[ERROR]   Property 'noAuto' does not exist on type 'IntrinsicAttributes & Partial<ThemedWebComponentProps<Upload, Readonly<{ onFileReject: EventName<UploadFileRejectEvent>; onUploadAbort: EventName<UploadAbortEvent>; ... 9 more ...; onMaxFilesReachedChanged: EventName<...>; }>>> & RefAttributes<...>'.
[ERROR] frontend/demo/component/upload/react/upload-all-files.tsx(28,65): error TS2339: Property 'uploadFiles' does not exist on type 'Upload'.
[ERROR] frontend/demo/component/upload/react/upload-auto-upload-disabled.tsx(16,23): error TS2339: Property 'i18n' does not exist on type '
[ERROR] ...
[ERROR] AbortEvent>; ... 9 more ...; onMaxFilesReachedChanged: EventName<...>; }>>> & RefAttributes<...>'.
[ERROR] frontend/demo/component/upload/react/upload-retry-button.tsx(17,13): error TS2322: Type '{ files: UploadFile[]; }' is not assignable to type 'IntrinsicAttributes & Partial<ThemedWebComponentProps<Upload, Readonly<{ onFileReject: EventName<UploadFileRejectEvent>; onUploadAbort: EventName<UploadAbortEvent>; ... 9 more ...; onMaxFilesReachedChanged: EventName<...>; }>>> & RefAttributes<...>'.
[ERROR]   Property 'files' does not exist on type 'IntrinsicAttributes & Partial<ThemedWebComponentProps<Upload, Readonly<{ onFileReject: EventName<UploadFileRejectEvent>; onUploadAbort: EventName<UploadAbortEvent>; ... 9 more ...; onMaxFilesReachedChanged: EventName<...>; }>>> & RefAttributes<...>'.
[ERROR] frontend/demo/component/upload/react/upload-start-button.tsx(24,13): error TS2322: Type '{ files: UploadFile[]; }' is not assignable to type 'IntrinsicAttributes & Partial<ThemedWebComponentProps<Upload, Readonly<{ onFileReject: EventName<UploadFileRejectEvent>; onUploadAbort: EventName<UploadAbortEvent>; ... 9 more ...; onMaxFilesReachedChanged: EventName<...>; }>>> & RefAttributes<...>'.
[ERROR]   Property 'files' does not exist on type 'IntrinsicAttributes & Partial<ThemedWebComponentProps<Upload, Readonly<{ onFileReject: EventName<UploadFileRejectEvent>; onUploadAbort: EventName<UploadAbortEvent>; ... 9 more ...; onMaxFilesReachedChanged: EventName<...>; }>>> & RefAttributes<...>'.
[ERROR] frontend/demo/component/upload/upload-all-files.ts(25,17): error TS2339: Property 'i18n' does not exist on type 'Upload'.
[ERROR] frontend/demo/component/upload/upload-all-files.ts(26,17): error TS2339: Property 'i18n' does not exist on type 'Upload'.
[ERROR] frontend/demo/component/upload/upload-all-files.ts(26,41): error TS2339: Property 'i18n' does not exist on type 'Upload'.
[ERROR] frontend/demo/component/upload/upload-all-files.ts(41,18): error TS2339: Property 'uploadFiles' does not exist on type 'Upload'.
[ERROR] frontend/demo/component/upload/upload-auto-upload-disabled.ts(24,17): error TS2339: Property 'i18n' does not exist on type 'Upload'.
[ERROR] frontend/demo/component/upload/upload-auto-upload-disabled.ts(25,17): error TS2339: Property 'i18n' does not exist on type 'Upload'.
[ERROR] frontend/demo/component/upload/upload-auto-upload-disabled.ts(25,41): error TS2339: Property 'i18n' does not exist on type 'Upload'.
[ERROR] frontend/demo/component/upload/upload-button-theme-variant.ts(31,17): error TS2339: Property 'i18n' does not exist on type 'Upload'.

```
