### PR TITLE
chore: update vaadin to 24.5.0.alpha5

### PR DESCRIPTION
**Pull request by manolo**
At the same time I needed to remove CE licensing demo and references to fix compilation errors

### CODE REVIEW

**Review by web-padawan — COMMENTED** [review]
We probably should not remove CE articles but just the block that mentions `MyVaadinInitListener`

**Comment by web-padawan** [comment]
The compilation is now fixed by moving the broken Java file in #3553. I will revert related changes from this PR.

**Review by web-padawan — APPROVED** [review]
LGTM. Tested locally after rebasing and `npm run dspublisher:start` works fine.
