### PR TITLE
feat: use signals in examples

### PR DESCRIPTION
**Pull request by cromoteca**
Hilla developers are now encouraged to use signals to manage state.

This PR updates the existing documentation to use signals instead of standard React hooks.

Closes https://github.com/vaadin/docs/issues/3173

### CODE REVIEW

**Comment by tarekoraby** [comment]
After rebasing on `next` branch, I see a lot of Signals-related errors when opening components articles (e.g., http://localhost:8000/components/confirm-dialog):

```
[TypeScript] Cannot find module '@vaadin/hilla-react-signals' or its corresponding type declarations.
```

image

**Comment by peholmst** [comment]
Heads up! There is a bigger restructuring of the articles in the `next` branch coming up. Unless you want to end up in merge hell, I suggest you merge this PR as soon as possible.

**Review by taefi — COMMENTED** [review]
Finished reviewing the second half of the changes:
- grid
- grid pro
- listbox
- login
- menubar
- messages
- multiselect combobox
- notification
- passwordfield
- radiobutton
- richtexteditor
- select
- splitlayout
- tabs
- textarea
- timepicker
- tooltip
- treegrid
- virtuallist
- form/formchange

There were a few files missing the `// tag-snippet []` so the code part wasn't showing any intended part of the code, and only when expanded, the whole code was shown (which is correct). I added the missing `// tag-snippet []` in a separate commit.

Only one thing wasn't working (which is not working on hilla.dev as well) is the subsequent fetches of lazy data in `frontent/demo/component/grid/grid-data-provider.tsx`. 

So, the stuff related to the changes in this PR is working fine IMO and good to be merged.

**Review by platosha — APPROVED** [review]
